# Generated by Django 5.1.2 on 2024-10-25 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='main',
            options={'verbose_name_plural': ''},
        ),
        migrations.AddField(
            model_name='main',
            name='image',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='main',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='main',
            name='banner_image',
            field=models.ImageField(upload_to='banners/'),
        ),
        migrations.AlterField(
            model_name='main',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
